pipeline:

  build:
    privileged: true
    image: docker
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t quay.io/ukhomeofficedigital/tf-testrunner:${DRONE_COMMIT_SHA} .

  image_to_quay:
    image: docker
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+tftestrunner" -p=${DOCKER_PASSWORD} quay.io
      - docker push quay.io/ukhomeofficedigital/tf-testrunner:${DRONE_COMMIT_SHA}


  test_example_implementation:
    image: quay.io/ukhomeofficedigital/tf-testrunner:${DRONE_COMMIT_SHA}
    commands:
      - cd examples/basic-proof
      - python -m unittest tests/*_test.py

  tag_as_latest_quay:
    image: docker
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+tftestrunner" -p=${DOCKER_PASSWORD} quay.io
      - docker tag quay.io/ukhomeofficedigital/tf-testrunner:${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/tf-testrunner:latest
      - docker push quay.io/ukhomeofficedigital/tf-testrunner:latest
    when:
      branch: master
      event: push

services:
  dind:
    image: docker:dind
    privileged: true
    command:
      - "-s"
      - "overlay"
